In [1]:
import numpy as np
import pandas as pd
import nltk
from nltk.corpus import stopwords
import string

In [106]:
df = pd.read_csv('C:/Users/Yash/Desktop/Fake News/fake_or_real_news.csv')

df.head(60)

Unnamed: 0                                              title  \
0         8476                       You Can Smell Hillary’s Fear   
1        10294  Watch The Exact Moment Paul Ryan Committed Pol...   
2         3608        Kerry to go to Paris in gesture of sympathy   
3        10142  Bernie supporters on Twitter erupt in anger ag...   
4          875   The Battle of New York: Why This Primary Matters   
5         6903                                        Tehran, USA   
6         7341  Girl Horrified At What She Watches Boyfriend D...   
7           95                  ‘Britain’s Schindler’ Dies at 106   
8         4869  Fact check: Trump and Clinton at the 'commande...   
9         2909  Iran reportedly makes new push for uranium con...   
10        1357  With all three Clintons in Iowa, a glimpse at ...   
11         988  Donald Trump’s Shockingly Weak Delegate Game S...   
12        7041  Strong Solar Storm, Tech Risks Today | S0 News...   
13        7623       10 Ways America Is Preparing for World War 3   
14        1571                   Trump takes on Cruz, but lightly   
15        4739                         How women lead differently   
16        7737  Shocking! Michele Obama & Hillary Caught Glamo...   
17        8716  Hillary Clinton in HUGE Trouble After America ...   
18        3304  What's in that Iran bill that Obama doesn't like?   
19        3078  The 1 chart that explains everything you need ...   
20        2517  The slippery slope to Trump’s proposed ban on ...   
21       10348  Episode #160 – SUNDAY WIRE: ‘Hail to the Deplo...   
22         778  Hillary Clinton Makes A Bipartisan Appeal on S...   
23        3300  New Senate majority leader’s main goal for GOP...   
24        6155              ‘Inferno’ and the Overpopulation Myth   
25         636  Anti-Trump forces seek last-ditch delegate revolt   
26         755  Sanders Trounces Clinton in W. Va. -- But Will...   
27         626  Donald Trump Is Changing His Campaign Slogan t...   
28         691  Pure chaos: Donald Trump’s campaign management...   
29        5743  Syrian War Report – November 1, 2016: Syrian M...   
30        1787                     GOP insiders: Carly crushed it   
31        7808  Jeffrey Sewell et al. : Metabiology face to fa...   
32        6484         Why It’s Necessary To Relax Into A Stretch   
33        7385  Brexit Encourages UK to Trade With Non-EU Stat...   
34        9016  2016 interview with Socrates: Another day of L...   
35        9324  Mike Pence Drapes Shawl Over Immodest Lady Jus...   
36        8983       First Ever Hindu Woman Elected into Congress   
37        8965  Donald Groped Hillary in 2005! Trump and Weine...   
38        5580  Ex-Assistant FBI Director: Clintons Are a Crim...   
39        9757  Hillary Wants Aggressively Interventionist For...   
40        1967  Both parties want to craft populist messages f...   
41         431  First Take: Wall Street bids goodbye to June hike   
42        5955  Real Disclosure! Secret Alien Base Found In Mo...   
43        7455  Homeless Woman Protects Trump’s Walk of Fame S...   
44        5224  With 3:20 a.m. tweet storm Saturday, Clinton c...   
45        7793  220 ‘Significant’ Pipeline Spills Already This...   
46        2777  Obama makes the right call to tough it out in ...   
47         587  Senate race rankings: Dems attack as GOP lays ...   
48        9403  ‘He didn’t know the boy didn’t want to be rape...   
49        5931  Pieczenik “Rogue FBI Agents and Wikileaks are ...   
50        3027    American politics has reached peak polarization   
51        4377  Anti-Muhammad cartoon contest: Free speech or ...   
52        5937  3 Effects of Substance Abuse on Individual, Fa...   
53        7277  Tree Shaped Vertical Farms That Grow 24 Acres ...   
54        5521               New Comment Features have been Added   
55        3627         World's newspapers react to 'Hebdo' attack   
56        9360         Ying and Yang (the Gold and Silver Set-Up)   
57

In [108]:
df.shape

(6335, 4)

In [109]:
df.columns

Index(['Unnamed: 0', 'title', 'text', 'label'], dtype='object')

In [110]:
df.drop_duplicates(inplace = True)

In [111]:
df.shape

(6335, 4)

In [112]:
df.loc[df["label"]=="FAKE","label"]=0
df.loc[df["label"]=="REAL","label"]=1

In [114]:
df.head(60)

Unnamed: 0                                              title  \
0         8476                       You Can Smell Hillary’s Fear   
1        10294  Watch The Exact Moment Paul Ryan Committed Pol...   
2         3608        Kerry to go to Paris in gesture of sympathy   
3        10142  Bernie supporters on Twitter erupt in anger ag...   
4          875   The Battle of New York: Why This Primary Matters   
5         6903                                        Tehran, USA   
6         7341  Girl Horrified At What She Watches Boyfriend D...   
7           95                  ‘Britain’s Schindler’ Dies at 106   
8         4869  Fact check: Trump and Clinton at the 'commande...   
9         2909  Iran reportedly makes new push for uranium con...   
10        1357  With all three Clintons in Iowa, a glimpse at ...   
11         988  Donald Trump’s Shockingly Weak Delegate Game S...   
12        7041  Strong Solar Storm, Tech Risks Today | S0 News...   
13        7623       10 Ways America Is Preparing for World War 3   
14        1571                   Trump takes on Cruz, but lightly   
15        4739                         How women lead differently   
16        7737  Shocking! Michele Obama & Hillary Caught Glamo...   
17        8716  Hillary Clinton in HUGE Trouble After America ...   
18        3304  What's in that Iran bill that Obama doesn't like?   
19        3078  The 1 chart that explains everything you need ...   
20        2517  The slippery slope to Trump’s proposed ban on ...   
21       10348  Episode #160 – SUNDAY WIRE: ‘Hail to the Deplo...   
22         778  Hillary Clinton Makes A Bipartisan Appeal on S...   
23        3300  New Senate majority leader’s main goal for GOP...   
24        6155              ‘Inferno’ and the Overpopulation Myth   
25         636  Anti-Trump forces seek last-ditch delegate revolt   
26         755  Sanders Trounces Clinton in W. Va. -- But Will...   
27         626  Donald Trump Is Changing His Campaign Slogan t...   
28         691  Pure chaos: Donald Trump’s campaign management...   
29        5743  Syrian War Report – November 1, 2016: Syrian M...   
30        1787                     GOP insiders: Carly crushed it   
31        7808  Jeffrey Sewell et al. : Metabiology face to fa...   
32        6484         Why It’s Necessary To Relax Into A Stretch   
33        7385  Brexit Encourages UK to Trade With Non-EU Stat...   
34        9016  2016 interview with Socrates: Another day of L...   
35        9324  Mike Pence Drapes Shawl Over Immodest Lady Jus...   
36        8983       First Ever Hindu Woman Elected into Congress   
37        8965  Donald Groped Hillary in 2005! Trump and Weine...   
38        5580  Ex-Assistant FBI Director: Clintons Are a Crim...   
39        9757  Hillary Wants Aggressively Interventionist For...   
40        1967  Both parties want to craft populist messages f...   
41         431  First Take: Wall Street bids goodbye to June hike   
42        5955  Real Disclosure! Secret Alien Base Found In Mo...   
43        7455  Homeless Woman Protects Trump’s Walk of Fame S...   
44        5224  With 3:20 a.m. tweet storm Saturday, Clinton c...   
45        7793  220 ‘Significant’ Pipeline Spills Already This...   
46        2777  Obama makes the right call to tough it out in ...   
47         587  Senate race rankings: Dems attack as GOP lays ...   
48        9403  ‘He didn’t know the boy didn’t want to be rape...   
49        5931  Pieczenik “Rogue FBI Agents and Wikileaks are ...   
50        3027    American politics has reached peak polarization   
51        4377  Anti-Muhammad cartoon contest: Free speech or ...   
52        5937  3 Effects of Substance Abuse on Individual, Fa...   
53        7277  Tree Shaped Vertical Farms That Grow 24 Acres ...   
54        5521               New Comment Features have been Added   
55        3627         World's newspapers react to 'Hebdo' attack   
56        9360         Ying and Yang (the Gold and Silver Set-Up)   
57

In [9]:
df.isnull().sum()

Unnamed: 0    0
title         0
text          0
label         0
dtype: int64

In [10]:
nltk.download('stopwords')

[nltk_data] Downloading package stopwords to
[nltk_data]     C:\Users\Yash\AppData\Roaming\nltk_data...
[nltk_data]   Package stopwords is already up-to-date!


True

In [11]:
def process_text(text):
    '''
    1. Remove punctuation
    2. Remove stopwords
    3. Return list of clean text words
    '''
    
    #1
    nopunc = [char for char in text if char not in string.punctuation]
    nopunc = ''.join(nopunc)
    
    #2
    clean_words = [word for word in nopunc.split() if word.lower() not in stopwords.words('english')]
    
    #3
    return clean_words

In [12]:
#Show the Tokenization 
df['text'].head().apply(process_text) 

0    [Daniel, Greenfield, Shillman, Journalism, Fel...
1    [Google, Pinterest, Digg, Linkedin, Reddit, St...
2    [US, Secretary, State, John, F, Kerry, said, M...
3    [—, Kaydee, King, KaydeeKing, November, 9, 201...
4    [primary, day, New, York, frontrunners, Hillar...
Name: text, dtype: object

In [13]:
from sklearn.feature_extraction.text import CountVectorizer
News = CountVectorizer(analyzer=process_text).fit_transform(df['text'])

In [54]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(News, df['label'], test_size = 0.40, random_state = 0)

In [55]:
#Get the shape of News
News.shape

(6335, 128019)

In [56]:
from sklearn.naive_bayes import MultinomialNB
classifier = MultinomialNB()
classifier.fit(X_train, y_train)

MultinomialNB(alpha=1.0, class_prior=None, fit_prior=True)

In [57]:
#Print the predictions
print(classifier.predict(X_train))

[0 0 0 ... 0 0 1]


In [58]:
#Print the actual values
print(y_train.values)

[0 0 0 ... 0 0 1]


In [59]:
#Evaluate the model on the training data set
from sklearn.metrics import classification_report,confusion_matrix, accuracy_score
pred = classifier.predict(X_train)
print(classification_report(y_train ,pred ))
print('Confusion Matrix: \n',confusion_matrix(y_train,pred))
print()
print('Accuracy: ', accuracy_score(y_train,pred))

              precision    recall  f1-score   support

           0       0.99      0.93      0.96      1897
           1       0.93      0.99      0.96      1904

    accuracy                           0.96      3801
   macro avg       0.96      0.96      0.96      3801
weighted avg       0.96      0.96      0.96      3801

Confusion Matrix: 
 [[1759  138]
 [  21 1883]]

Accuracy:  0.9581689029202841


In [60]:
 #Print the predictions
print('Predicted value: ',classifier.predict(X_test))

Predicted value:  [1 1 0 ... 0 1 0]


In [61]:
#Print Actual Label
print('Actual value: ',y_test.values)

Actual value:  [1 0 0 ... 0 1 0]


In [62]:
#Evaluate the model on the test data set
from sklearn.metrics import classification_report,confusion_matrix, accuracy_score
pred = classifier.predict(X_test)
print(classification_report(y_test ,pred ))

print('Confusion Matrix: \n', confusion_matrix(y_test,pred))
print()
print('Accuracy: ', accuracy_score(y_test,pred))


              precision    recall  f1-score   support

           0       0.94      0.85      0.90      1267
           1       0.86      0.95      0.91      1267

    accuracy                           0.90      2534
   macro avg       0.90      0.90      0.90      2534
weighted avg       0.90      0.90      0.90      2534

Confusion Matrix: 
 [[1078  189]
 [  63 1204]]

Accuracy:  0.9005524861878453


In [63]:
from sklearn.ensemble import RandomForestClassifier

In [64]:
clf1 = RandomForestClassifier(random_state=1)
clf1.fit(X_train, y_train)

RandomForestClassifier(bootstrap=True, class_weight=None, criterion='gini',
                       max_depth=None, max_features='auto', max_leaf_nodes=None,
                       min_impurity_decrease=0.0, min_impurity_split=None,
                       min_samples_leaf=1, min_samples_split=2,
                       min_weight_fraction_leaf=0.0, n_estimators=10,
                       n_jobs=None, oob_score=False, random_state=1, verbose=0,
                       warm_start=False)

In [65]:
#Print the predictions
print(clf1.predict(X_train))

[0 0 0 ... 0 0 1]


In [66]:
#Print the actual values
print(y_train.values)

[0 0 0 ... 0 0 1]


In [67]:
#Evaluate the model on the training data set
from sklearn.metrics import classification_report,confusion_matrix, accuracy_score
pred = clf1.predict(X_train)
print(classification_report(y_train ,pred ))
print('Confusion Matrix: \n',confusion_matrix(y_train,pred))
print()
print('Accuracy: ', accuracy_score(y_train,pred))

              precision    recall  f1-score   support

           0       0.99      1.00      0.99      1897
           1       1.00      0.99      0.99      1904

    accuracy                           0.99      3801
   macro avg       0.99      0.99      0.99      3801
weighted avg       0.99      0.99      0.99      3801

Confusion Matrix: 
 [[1894    3]
 [  22 1882]]

Accuracy:  0.9934227834780321


In [68]:
 #Print the predictions
print('Predicted value: ',clf1.predict(X_test))

Predicted value:  [1 1 0 ... 0 1 0]


In [69]:
#Print Actual Label
print('Actual value: ',y_test.values)

Actual value:  [1 0 0 ... 0 1 0]


In [70]:
#Evaluate the model on the test data set
from sklearn.metrics import classification_report,confusion_matrix, accuracy_score
pred = clf1.predict(X_test)
print(classification_report(y_test ,pred ))

print('Confusion Matrix: \n', confusion_matrix(y_test,pred))
print()
print('Accuracy: ', accuracy_score(y_test,pred))


              precision    recall  f1-score   support

           0       0.83      0.83      0.83      1267
           1       0.83      0.83      0.83      1267

    accuracy                           0.83      2534
   macro avg       0.83      0.83      0.83      2534
weighted avg       0.83      0.83      0.83      2534

Confusion Matrix: 
 [[1054  213]
 [ 218 1049]]

Accuracy:  0.82991318074191


In [71]:
from sklearn.ensemble import BaggingClassifier,AdaBoostClassifier,VotingClassifier
from sklearn.tree import DecisionTreeClassifier 
from sklearn import model_selection
from sklearn.linear_model import LogisticRegression
from sklearn.svm import SVC

In [72]:
#descision tree
dt = DecisionTreeClassifier(criterion='gini',max_depth=None)
dt.fit(X_train,y_train)

DecisionTreeClassifier(class_weight=None, criterion='gini', max_depth=None,
                       max_features=None, max_leaf_nodes=None,
                       min_impurity_decrease=0.0, min_impurity_split=None,
                       min_samples_leaf=1, min_samples_split=2,
                       min_weight_fraction_leaf=0.0, presort=False,
                       random_state=None, splitter='best')

In [73]:
# dt.score(X_test,y_test)
#Print the predictions
print(dt.predict(X_train))

[0 0 0 ... 0 0 1]


In [74]:
# dt.score(X_train,y_train)
#Print the actual values
print(y_train.values)

[0 0 0 ... 0 0 1]


In [75]:
predictions = dt.predict(X_test)

In [76]:
from sklearn.metrics import classification_report,confusion_matrix

In [77]:
print(classification_report(y_test,predictions))

              precision    recall  f1-score   support

           0       0.84      0.80      0.82      1267
           1       0.81      0.85      0.83      1267

    accuracy                           0.83      2534
   macro avg       0.83      0.83      0.83      2534
weighted avg       0.83      0.83      0.83      2534



In [78]:
cm=confusion_matrix(y_test,predictions)
print(cm)
print ("Accuracy of prediction:",accuracy_score(y_test,pred))

[[1019  248]
 [ 195 1072]]
Accuracy of prediction: 0.82991318074191


In [79]:
#Evaluate the model on the training data set
from sklearn.metrics import classification_report,confusion_matrix, accuracy_score
pred = dt.predict(X_train)
print(classification_report(y_train ,pred ))
print('Confusion Matrix: \n',confusion_matrix(y_train,pred))
print()
print('Accuracy: ', accuracy_score(y_train,pred))

              precision    recall  f1-score   support

           0       1.00      1.00      1.00      1897
           1       1.00      1.00      1.00      1904

    accuracy                           1.00      3801
   macro avg       1.00      1.00      1.00      3801
weighted avg       1.00      1.00      1.00      3801

Confusion Matrix: 
 [[1897    0]
 [   0 1904]]

Accuracy:  1.0


In [80]:
 #Print the predictions
print('Predicted value: ',dt.predict(X_test))

Predicted value:  [1 0 0 ... 1 1 0]


In [81]:
#Print Actual Label
print('Actual value: ',y_test.values)

Actual value:  [1 0 0 ... 0 1 0]


In [82]:
#Evaluate the model on the test data set
from sklearn.metrics import classification_report,confusion_matrix, accuracy_score
pred = dt.predict(X_test)
print(classification_report(y_test ,pred ))

print('Confusion Matrix: \n', confusion_matrix(y_test,pred))
print()
print('Accuracy: ', accuracy_score(y_test,pred))


              precision    recall  f1-score   support

           0       0.84      0.80      0.82      1267
           1       0.81      0.85      0.83      1267

    accuracy                           0.83      2534
   macro avg       0.83      0.83      0.83      2534
weighted avg       0.83      0.83      0.83      2534

Confusion Matrix: 
 [[1019  248]
 [ 195 1072]]

Accuracy:  0.8251775848460932


In [83]:
#Bagging 

bg = BaggingClassifier(DecisionTreeClassifier(), max_samples= 0.5, max_features = 1.0, n_estimators = 20)
bg.fit(X_train,y_train)

BaggingClassifier(base_estimator=DecisionTreeClassifier(class_weight=None,
                                                        criterion='gini',
                                                        max_depth=None,
                                                        max_features=None,
                                                        max_leaf_nodes=None,
                                                        min_impurity_decrease=0.0,
                                                        min_impurity_split=None,
                                                        min_samples_leaf=1,
                                                        min_samples_split=2,
                                                        min_weight_fraction_leaf=0.0,
                                                        presort=False,
                                                        random_state=None,
                                                        splitter='best'),
    

In [84]:
bg.score(X_test,y_test)

0.8823993685872139

In [85]:
bg.score(X_train,y_train)

0.9707971586424625

In [86]:
#Boosting - Ada Boost

adb = AdaBoostClassifier(DecisionTreeClassifier(),n_estimators = 5, learning_rate = 1)
adb.fit(X_train,y_train)

AdaBoostClassifier(algorithm='SAMME.R',
                   base_estimator=DecisionTreeClassifier(class_weight=None,
                                                         criterion='gini',
                                                         max_depth=None,
                                                         max_features=None,
                                                         max_leaf_nodes=None,
                                                         min_impurity_decrease=0.0,
                                                         min_impurity_split=None,
                                                         min_samples_leaf=1,
                                                         min_samples_split=2,
                                                         min_weight_fraction_leaf=0.0,
                                                         presort=False,
                                                         random_state=None,
                          

In [87]:
adb.score(X_test,y_test)

0.8287292817679558

In [88]:
adb.score(X_train,y_train)

1.0

In [89]:
pip install mlxtend

Note: you may need to restart the kernel to use updated packages.


In [90]:
from mlxtend.classifier import StackingClassifier
from sklearn.neighbors import KNeighborsClassifier

In [91]:
import warnings

warnings.simplefilter('ignore')

In [92]:
clf1 = KNeighborsClassifier(n_neighbors=1)
clf2 = RandomForestClassifier(random_state=1)
clf3 = MultinomialNB()
lr   = LogisticRegression()
sclf = StackingClassifier(classifiers=[clf1, clf2, clf3], 
                          meta_classifier=lr)

In [94]:
print('4-fold cross validation:\n')

for clf, label in zip([clf1, clf2, clf3,lr, sclf], 
                      ['KNN', 
                       'Random Forest', 
                       'Naive Bayes',
                       'Logistic Regression','StackingClassifier']):

    scores = model_selection.cross_val_score(clf, X_train, y_train,cv=4, scoring='accuracy')
    print("Accuracy: %0.2f (+/- %0.2f) [%s]" 
          % (scores.mean(), scores.std(), label))

4-fold cross validation:

Accuracy: 0.78 (+/- 0.00) [KNN]
Accuracy: 0.84 (+/- 0.00) [Random Forest]
Accuracy: 0.90 (+/- 0.01) [Naive Bayes]
Accuracy: 0.92 (+/- 0.01) [Logistic Regression]
Accuracy: 0.81 (+/- 0.03) [StackingClassifier]


In [95]:
print('4-fold cross validation:\n')

for clf, label in zip([clf1, clf2, clf3,lr, sclf], 
                      ['KNN', 
                       'Random Forest', 
                       'Naive Bayes',
                       'Logistic Regression','StackingClassifier']):

    scores = model_selection.cross_val_score(clf, X_test, y_test,cv=4, scoring='accuracy')
    print("Accuracy: %0.2f (+/- %0.2f) [%s]" 
          % (scores.mean(), scores.std(), label))

4-fold cross validation:

Accuracy: 0.75 (+/- 0.01) [KNN]
Accuracy: 0.81 (+/- 0.01) [Random Forest]
Accuracy: 0.88 (+/- 0.01) [Naive Bayes]
Accuracy: 0.90 (+/- 0.00) [Logistic Regression]
Accuracy: 0.79 (+/- 0.02) [StackingClassifier]


In [99]:
bg.score(X_test,y_test) # bagging 

0.8823993685872139

In [100]:
adb.score(X_test,y_test)  # Boosting

0.8287292817679558

In [101]:
# Stacking
print('4-fold cross validation:\n')

for clf, label in zip([clf1, clf2, clf3,lr, sclf], 
                      ['KNN', 
                       'Random Forest', 
                       'Naive Bayes',
                       'Logistic Regression','StackingClassifier']):

    scores = model_selection.cross_val_score(clf, X_test, y_test,cv=4, scoring='accuracy')
    print("Accuracy: %0.2f (+/- %0.2f) [%s]" 
          % (scores.mean(), scores.std(), label))

4-fold cross validation:

Accuracy: 0.75 (+/- 0.01) [KNN]
Accuracy: 0.81 (+/- 0.01) [Random Forest]
Accuracy: 0.88 (+/- 0.01) [Naive Bayes]
Accuracy: 0.90 (+/- 0.00) [Logistic Regression]
Accuracy: 0.79 (+/- 0.02) [StackingClassifier]


In [117]:
News

<6335x128019 sparse matrix of type '<class 'numpy.int64'>'
	with 1927260 stored elements in Compressed Sparse Row format>